/*
 * This codes is licensed under CC0 1.0 Universal
 */

#JS = loaddll( hidemarudir + @"\hmV8.dll" );

#_ = dllfuncw( #JS, "DoFile", currentmacrodirectory + @"\HmAbstractTranslator.js");
#_ = dllfuncw( #JS, "DoFile", currentmacrodirectory + @"\HmBaiduTranslator.js");
#_ = dllfuncw( #JS, "DoString", R"JS(
    // Baidu翻訳を利用して、言語自動判別 ⇒ 日本語へ
    let result_words = ContextTranslator.Translate(BaiduTranslatorQueryStrategy, { src: "auto", dst: "jp" });

)JS"
);

freedll( #JS );