#JS = loaddll( hidemarudir + @"\hmV8.dll" );

#_ = dllfuncw( #JS, "DoFile", currentmacrodirectory + @"\HmAbstractTranslator.js");
#_ = dllfuncw( #JS, "DoFile", currentmacrodirectory + @"\HmGoogleTranslator.js");
#_ = dllfuncw( #JS, "DoString", R"JS(
    // Google翻訳を利用して、言語自動判別 ⇒ 日本語へ
    let result_words = ContextTranslator.Translate(GoogleTranslatorQueryStrategy, { src: "auto", dst: "ja" });

)JS"
);

freedll( #JS );