/*
 * This codes is licensed under CC0 1.0 Universal
 */

#JS = loaddll( hidemarudir + @"\hmV8.dll" );

#_ = dllfuncw( #JS, "DoFile", currentmacrodirectory + @"\HmAbstractTranslator.js");
#_ = dllfuncw( #JS, "DoFile", currentmacrodirectory + @"\HmGoogleTranslator.js");
#_ = dllfuncw( #JS, "DoString", R"JS(
    // Google翻訳を利用して、言語自動判別 ⇒ 英語へ
    let result_words = ContextTranslator.Translate(GoogleTranslatorQueryStrategy, { src: "auto", dst: "en" });

)JS"
);

freedll( #JS );