//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.IronLua.Properties
{
    using System;

    internal class Resources
    {
        /// <summary>
        ///   No conversion defined from {0} to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsBindConversionNotDefined
        {
            get
            {
                return "No conversion defined from {0} to {1}.";
            }
        }

        /// <summary>
        ///   No operator is defined for {1} {0} {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsBindOperatorNotDefined
        {
            get
            {
                return "No operator is defined for {1} {0} {2}.";
            }
        }

        /// <summary>
        ///   Chunk is not compiled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsChunkNotCompiled
        {
            get
            {
                return "Chunk is not compiled.";
            }
        }

        /// <summary>
        ///   Chunk is compiled in a differend script-manager. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsChunkWrongScriptManager
        {
            get
            {
                return "Chunk is compiled in a differend script-manager.";
            }
        }

        /// <summary>
        ///   No type for the generic argument {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsClrGenericNoType
        {
            get
            {
                return "No type for the generic argument {0}.";
            }
        }

        /// <summary>
        ///   Clr type expected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsClrGenericTypeExpected
        {
            get
            {
                return "Clr type expected.";
            }
        }

        /// <summary>
        ///   Constant expression could not evaluate ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsConstExpressionEvalError
        {
            get
            {
                return "Constant expression could not evaluate ({0}).";
            }
        }

        /// <summary>
        ///   Constant expression expected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsConstExpressionNeeded
        {
            get
            {
                return "Constant expression expected.";
            }
        }

        /// <summary>
        ///   Argument ar must from the same LuaThread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsCoroutineInvalidAR
        {
            get
            {
                return "Argument ar must from the same LuaThread.";
            }
        }

        /// <summary>
        ///   Argument co must be a LuaThread or a Thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsCoroutineInvalidCO
        {
            get
            {
                return "Argument co must be a LuaThread or a Thread.";
            }
        }

        /// <summary>
        ///   BeginResume is not called. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsCoroutineNoBeginResume
        {
            get
            {
                return "BeginResume is not called.";
            }
        }

        /// <summary>
        ///   Yield from wrong thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsCoroutineWrongThread
        {
            get
            {
                return "Yield from wrong thread.";
            }
        }

        /// <summary>
        ///   Delegate must not have out parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsDelegateCouldNotHaveOut
        {
            get
            {
                return "Delegate must not have out parameters.";
            }
        }

        /// <summary>
        ///   Expression is not enumerable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsExpressionNotEnumerable
        {
            get
            {
                return "Expression is not enumerable.";
            }
        }

        /// <summary>
        ///   Invalid mode format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsFileInvalidModeFormat
        {
            get
            {
                return "Invalid mode format.";
            }
        }

        /// <summary>
        ///   Can not read from file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsFileNotReadable
        {
            get
            {
                return "Can not read from file.";
            }
        }

        /// <summary>
        ///   File pointer can not set to a new position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsFileNotSeekable
        {
            get
            {
                return "File pointer can not set to a new position.";
            }
        }

        /// <summary>
        ///   Can not write into file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsFileNotWriteable
        {
            get
            {
                return "Can not write into file.";
            }
        }

        /// <summary>
        ///   Can not format &apos;{0}&apos; to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsFormatError
        {
            get
            {
                return "Can not format '{0}' to {1}.";
            }
        }

        /// <summary>
        ///   Function &apos;{0}&apos; on type &apos;{1}&apos; already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsGlobalFunctionNotUnique
        {
            get
            {
                return "Function '{0}' on type '{1}' already exists.";
            }
        }

        /// <summary>
        ///   No index found for type &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsIndexNotFound
        {
            get
            {
                return "No index found for type '{0}'.";
            }
        }

        /// <summary>
        ///   Type &apos;{0}&apos; is not callable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsInvokeNoDelegate
        {
            get
            {
                return "Type '{0}' is not callable.";
            }
        }

        /// <summary>
        ///   &apos;{0}:{1}&apos; is not readable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsMemberNotReadable
        {
            get
            {
                return "'{0}:{1}' is not readable.";
            }
        }

        /// <summary>
        ///   &apos;{0}:{1}&apos; not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsMemberNotResolved
        {
            get
            {
                return "'{0}:{1}' not found.";
            }
        }

        /// <summary>
        ///   &apos;{0}:{1}&apos; must be unique. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsMemberNotUnique
        {
            get
            {
                return "'{0}:{1}' must be unique.";
            }
        }

        /// <summary>
        ///   &apos;{0}:{1}&apos; is not writable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsMemberNotWritable
        {
            get
            {
                return "'{0}:{1}' is not writable.";
            }
        }

        /// <summary>
        ///   Can not mix static and non-static methods ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsMethodStaticMix
        {
            get
            {
                return "Can not mix static and non-static methods ({0}).";
            }
        }

        /// <summary>
        ///   Can not call nil value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsNilNotCallable
        {
            get
            {
                return "Can not call nil value.";
            }
        }

        /// <summary>
        ///   Operator is not defined for nil-values. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsNilOperatorError
        {
            get
            {
                return "Operator is not defined for nil-values.";
            }
        }

        /// <summary>
        ///   No length for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsNoLengthOperator
        {
            get
            {
                return "No length for {0}.";
            }
        }

        /// <summary>
        ///   Object is nil. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsNullReference
        {
            get
            {
                return "Object is nil.";
            }
        }

        /// <summary>
        ///   Number expected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsNumberExpected
        {
            get
            {
                return "Number expected.";
            }
        }

        /// <summary>
        ///   Assignment expected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseAssignmentExpected
        {
            get
            {
                return "Assignment expected.";
            }
        }

        /// <summary>
        ///   Number expected (&apos;{0}&apos; not converted). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseConvertNumberError
        {
            get
            {
                return "Number expected ('{0}' not converted).";
            }
        }

        /// <summary>
        ///   Current block is closed before end of file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseEof
        {
            get
            {
                return "Current block is closed before end of file.";
            }
        }

        /// <summary>
        ///   Expression has no result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseExpressionNoResult
        {
            get
            {
                return "Expression has no result.";
            }
        }

        /// <summary>
        ///   Expression is not assignable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseExpressionNotAssignable
        {
            get
            {
                return "Expression is not assignable.";
            }
        }

        /// <summary>
        ///   Unexpected char. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseInvalidChar
        {
            get
            {
                return "Unexpected char.";
            }
        }

        /// <summary>
        ///   Comment not closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseInvalidComment
        {
            get
            {
                return "Comment not closed.";
            }
        }

        /// <summary>
        ///   NewLine in string constant. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseInvalidString
        {
            get
            {
                return "NewLine in string constant.";
            }
        }

        /// <summary>
        ///   No arglist defined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseNoArgList
        {
            get
            {
                return "No arglist defined.";
            }
        }

        /// <summary>
        ///   It is not allowed to redefine the type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseTypeRedef
        {
            get
            {
                return "It is not allowed to redefine the type.";
            }
        }

        /// <summary>
        ///   Unexpected token &apos;{0}&apos;. &apos;{1}&apos; expected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseUnexpectedToken
        {
            get
            {
                return "Unexpected token '{0}'. '{1}' expected.";
            }
        }

        /// <summary>
        ///   Unexpected token in Else-Statement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseUnexpectedTokenElse
        {
            get
            {
                return "Unexpected token in Else-Statement";
            }
        }

        /// <summary>
        ///   Literal, function or tablector expected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseUnexpectedTokenPrefix
        {
            get
            {
                return "Literal, function or tablector expected.";
            }
        }

        /// <summary>
        ///   Type &apos;{0}&apos; not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsParseUnknownType
        {
            get
            {
                return "Type '{0}' not found.";
            }
        }

        /// <summary>
        ///    at  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsStackTraceAt
        {
            get
            {
                return "at ";
            }
        }

        /// <summary>
        ///    -- internal -- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsStackTraceInternal
        {
            get
            {
                return "-- internal --";
            }
        }

        /// <summary>
        ///    line  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsStackTraceLine
        {
            get
            {
                return " line ";
            }
        }

        /// <summary>
        ///   &lt;unknown method&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsStackTraceUnknownMethod
        {
            get
            {
                return "<unknown method>";
            }
        }

        /// <summary>
        ///   There is already a value with the key &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTableAddDuplicate
        {
            get
            {
                return "There is already a value with the key '{0}'.";
            }
        }

        /// <summary>
        ///   Failed to call &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTableCallMemberFailed
        {
            get
            {
                return "Failed to call '{0}'.";
            }
        }

        /// <summary>
        ///   Nil is not a valid key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTableKeyNotNullable
        {
            get
            {
                return "Nil is not a valid key.";
            }
        }

        /// <summary>
        ///   Methods must have a LuaTable as first parameter (&apos;{0}&apos;). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTableMethodExpected
        {
            get
            {
                return "Methods must have a LuaTable as first parameter ('{0}').";
            }
        }

        /// <summary>
        ///   Operator &apos;{0}&apos; is not compatible (expected {1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTableOperatorIncompatible
        {
            get
            {
                return "Operator '{0}' is not compatible (expected {1}).";
            }
        }

        /// <summary>
        ///   Operator &apos;{0}&apos; is not defined for the table. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTableOperatorNotFound
        {
            get
            {
                return "Operator '{0}' is not defined for the table.";
            }
        }

        /// <summary>
        ///   Name for type alias is invalid &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTypeAliasInvalidName
        {
            get
            {
                return "Name for type alias is invalid '{0}'.";
            }
        }

        /// <summary>
        ///   Method {0}.{1} must be static, public and needs at least one parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTypeExtentionInvalidMethod
        {
            get
            {
                return "Method {0}.{1} must be static, public and needs at least one parameter.";
            }
        }

        /// <summary>
        ///   {0} is not static. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rsTypeExtentionInvalidType
        {
            get
            {
                return "{0} is not static.";
            }
        }
    }
}
