/*
 * Copyright (c) 2017 Akitsugu Komiyama
 * under the Apache License Version 2.0
 */

#dllsop = loaddll( hidemarudir + "\\HmSharedOutputPane.dll");

if(#dllsop) {
	#_ = dllfunc( #dllsop, "SetHidemaruHandle", hidemaruhandle(0) ); // 現在の秀丸ウィンドウハンドルの伝達
	#_ = dllfunc( #dllsop, "SetWithClearTime", -1 );                 // 新しいOutput枠を出す際に、前回のOutputから何ミリ秒経過するとクリアするか
} else {
	message("HmSharedOutputPane.dllが導入されていません。");
}

// ★ #dllsopをマクロ内で手動でfreedllしてはならない!! 秀丸が閉じられるとfreedllされます。