#HMNET = loaddll( hidemarudir + @"\hm.NET.dll");

if (#HMNET) {
	#_ = dllfuncw(#HMNET, "SetDetachMethod", currentmacrodirectory + @"\HmHtmlPreviewChrome.dll", "HmHtmlPreviewChrome", "OnDetachMethod");

	##mode = 1; // 1: Fileƒ‚[ƒh
    #_ = dllfuncw(#HMNET, "CallMethod", currentmacrodirectory + @"\HmHtmlPreviewChrome.dll", "HmHtmlPreviewChrome", "Show", hidemaruhandle(0), ##mode );
} else {
    message("Hm.NET.dll‚ğ“Ç‚İ‚Ş‚±‚Æ‚ªo—ˆ‚Ü‚¹‚ñ");
}


