/*
 * CC0 1.0 Universal
 * このファイルは自動起動マクロから呼び出す際のサンプルです。
 * 自由にお使いください。
 */

if (event == 1 ) {
    if (filetype == ".xls" || filetype == ".xlsx" ) {
        // 閉じるので先にExcelファイルの名前をとっておく
        $$openedXlsFileName = filename2;
        // 閉じる
        closenew;

        execmacro currentmacrodirectory + @"\HmExcelFileLoader.mac", $$openedXlsFileName;
        // execmacro hidemarudir + @"\HmExcelFileLoader\HmExcelFileLoader.mac", $$openedXlsFileName;
    }
}