// このファイルは自動起動マクロから呼び出す際のサンプルでです。
// パブリックドメインとなります。自由にお使いください。

if (event == 1 ) {
    if(filetype == ".xls" || filetype == ".xlsx" ) {
        // 閉じるので先にExcelファイルの名前をとっておく
        $$dummyXlsFileName = filename2;
        // 閉じる
        closenew;

        execmacro currentmacrodirectory + @"\HmExcelFileLoader.mac", $$dummyXlsFileName;
        // execmacro hidemarudir + @"\HmExcelFileLoader\HmExcelFileLoader.mac", $$dummyXlsFileName;
    }
}