//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hmPython3.rc

#include "patchlevel.h"

// 新しいオブジェクトの次の既定値
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif


#define MAKE_RESOURCE_STR_(x) #x
#define MAKE_RESOURCE_STR(x) MAKE_RESOURCE_STR_(x)

#define MAKE_TARGET_PYTHON_VERSION_STR   "v" MAKE_RESOURCE_STR(PY_MAJOR_VERSION) "." MAKE_RESOURCE_STR(PY_MINOR_VERSION) "." MAKE_RESOURCE_STR(PY_MICRO_VERSION) " / " "python" MAKE_RESOURCE_STR(PY_MAJOR_VERSION) MAKE_RESOURCE_STR(PY_MINOR_VERSION) ".dll" " 用"


#define HM_PYTHON_MAJOR_VERION    2
#define HM_PYTHON_MINOR_VERION    0
#define HM_PYTHON_MICRO_VERION    0
#define HM_PYTHON_RELEASE_VERION  1

#define MAKE_TARGET_HM_PYTHON_VERSION_STR   MAKE_RESOURCE_STR(HM_PYTHON_MAJOR_VERION) "." MAKE_RESOURCE_STR(HM_PYTHON_MINOR_VERION) "." MAKE_RESOURCE_STR(HM_PYTHON_MICRO_VERION) "." MAKE_RESOURCE_STR(HM_PYTHON_RELEASE_VERION)
