; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24218.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\0300002167\AppData\Local\Temp\.NETFramework,Version=4.0.AssemblyAttributes.cpp"
