#HMNET = loaddll( hidemarudir + @"\hm.NET.dll");

if (#HMNET) {
	#_ = dllfuncw(#HMNET, "SetDetachMethod", currentmacrodirectory + @"\HmHtmlPreview.dll", "HmHtmlPreview", "OnDetachMethod");

	##mode = 0; // 0: Liveƒ‚[ƒh
    #_ = dllfuncw(#HMNET, "CallMethod", currentmacrodirectory + @"\HmHtmlPreview.dll", "HmHtmlPreview", "Show", hidemaruhandle(0), ##mode );
} else {
    message("Hm.NET.dll‚ğ“Ç‚İ‚Ş‚±‚Æ‚ªo—ˆ‚Ü‚¹‚ñ");
}


