; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

; Generated by VC++ for Common Language Runtime
.file "G:\repogitory\hidemaru-net\win-hidemaru-app\hm_edgejs\hmEdgeJS.src\hmEdgeJS\x64\Release\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
