; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27045.0 

; Generated by VC++ for Common Language Runtime
.file "G:\repogitory\hidemaru-net\win-hidemaru-app\hm_customlivepreview\HmCustomLivePreview.src\hmJS\x64\Release\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
